### ISSUE TITLE
Consistent date convention for periandi

### ISSUE THREAD

**Issue by oh-kay-blanket** [RobSis/middle-earth-genealogy-project#1]
Hi there. I love what you've done and would like to try visualizing some of these in a 3D GEDCOM viewer I am working on <https://github.com/mister-blanket/roots>. I've tried using the periandi.ged file to test, but the very large gaps in some of the birth dates makes it difficult to view. From what I can tell, it seems you are using mostly Shire Reckoning, but for a few of the important hobbits are using TA Reckoning. Do you, by chance, have any version of the file which uses a single reckoning? If not, I might look into making one, I just thought I'd check first. Thanks for your hard work!

**Comment by RobSis** [comment]
Hey, thanks for the kind words! The app looks amazing.

I guess it does make sense to convert all hobbits' dates into Shire Reckoning.

However, for visualizing other files, some kind of conversion would have to be made anyway. We can't use single Reckoning for all dates, because the exact number of years in First Age is not known.

**Comment by oh-kay-blanket** [comment]
I saw that you updated to SR; thanks for that. I forked this and will have a go with some of the other files to test them out. If I do any conversion, I'll send a pull request to share.
